//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "configs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub submission_start: Option<DateTimeWithTimeZone>,
    pub submission_end: Option<DateTimeWithTimeZone>,
    pub voting_start: Option<DateTimeWithTimeZone>,
    pub voting_end: Option<DateTimeWithTimeZone>,
    pub show_leaderboard: bool,
    pub assigned: bool,
    pub created_scores: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
