//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::admins::Entity as Admins;
pub use super::configs::Entity as Configs;
pub use super::submissions::Entity as Submissions;
pub use super::users::Entity as Users;
pub use super::vote_assignments::Entity as VoteAssignments;
pub use super::votes::Entity as Votes;
